[package]
name = "spoilerowobot"
version = "0.4.0"
authors = ["Lara"]
edition = "2018"

[dependencies]
futures-util = "0.3.6"
lazy_static = "1.4.0"
rand = "0.8.3"
regex = "1"
tbot = "0.6.7"
tokio = { version = "0.2", features = ["macros", "fs"] }